image:
  file: .gitpod.Dockerfile
tasks:
  - name: install package and check zsh and zsh plugin
    init: |-
      sudo chmod +x ./.gitpod/oh-my-zsh.sh && ./.gitpod/oh-my-zsh.sh
      pipenv --python 3.8
      pipenv install --dev
  - name: change default shell to zsh and start zsh shell
    command: sudo chsh -s $(which zsh) && zsh
github:
  prebuilds:
    addCheck: true
    addBadge: true
    addLabel: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
vscode:
  extensions:
    - streetsidesoftware.code-spell-checker-spanish
    - ms-python.python
