name: Deploy
on:
  workflow_dispatch: { }
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      CI: "true"
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev
      - name: Run test suite
        run: |
          pipenv run tests
      - name: Package and ready for distribution
        run: |
          pipenv run python3 setup.py bdist_wheel
      - name: Upload to pypi
        run: |
          pipenv run twine upload dist/* -u __token__ -p ${PYPI_PASSWORD}